# Generated by Django 3.2.8 on 2021-10-22 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_number_plate', '0002_alter_car_data_entry_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Driver Name')),
                ('phone', models.CharField(max_length=300, null=True, verbose_name='Phone')),
                ('address', models.CharField(max_length=300, null=True, verbose_name='Address')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='drivers', verbose_name='Driver Photo')),
                ('modify_time', models.DateTimeField()),
                ('data_entry_time', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='car_number_plate.car')),
            ],
        ),
    ]
