# Generated by Django 3.2.8 on 2021-10-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_number_plate', '0003_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='plate_photo',
            field=models.ImageField(blank=True, default='platepic.png', null=True, upload_to='plate_pic', verbose_name='Number Plate Image'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='photo',
            field=models.ImageField(blank=True, default='driverpic.png', null=True, upload_to='driver_pic', verbose_name='Driver Photo'),
        ),
    ]
